version: '2'
services:
    demomysql-app:
        image: demomysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demomysql-mysql:3306/demomysql?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demomysql-mysql:
        extends:
            file: mysql.yml
            service: demomysql-mysql
